
const Main = () => {
  return (
    <div className="main">
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
      Main <br />
    </div>
  )
}

export default Main